version: "3.8"
services:
  ui:
    build: ./UI
    links:
      - engine
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    networks:
      - flask-network
  engine:
    build: ./Engine
    links:
      - mysql
    depends_on:
      - mysql
    ports:
      - "5001:5001"
    environment:
      DB_NAME: database_drs
      DB_USER: root
      DB_PASSWORD: Slatkamalasladakja123!
    volumes:
      - ./Engine:/app
    networks:
      - flask-network
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Slatkamalasladakja123!
    volumes:
      - ./DB:/docker-entrypoint-initdb.d/:ro
      - mysql-data:/var/lib/mysql
    networks:
      - flask-network

volumes:
  mysql-data:
    driver: local

networks:
  flask-network: